### ISSUE TITLE
Windows bad

### ISSUE THREAD

**Issue by Cyb3rTrash** [Cyb3rTrash/better_osu_scraper#3]
Breaks on windows with certain non ascii characters

**Comment by myangelaku** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 windows bad 六四天安門事件 ascii charactera 天安門大屠殺 "better"反右osu scraper派鬥爭

**Comment by Cyb3rTrash** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 hallowatcher 하러와차 六四天安門事件 (((utf-8))) 天安門大屠殺 2021 incident 反右 install gentoo 派鬥爭
